name: street
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  socket_io_client: ^3.1.3
  flame: ^1.34.0
  just_audio: ^0.9.36
  google_sign_in: ^6.1.5
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/